### ISSUE TITLE
mirror degradation of LST1 is propagated to MAGIC

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/lst-sim-config#34]
when the mirror degradation of LST1 was changed from the camera_transmission to mirror_degradation it affected MAGIC as well - this value was not set for MAGIC telescopes (the whole degradation was in camera_transmission), so the setting got propagated since MAGIC is simulated after LST and the light in both MAGIC telescopes is underestimated by 22%

**Comment by moralejo** [comment]
@Voutsi :  I think that once this is fixed in the MAGIC configuration, and whatever other MAGIC settings that need updating are **blessed by @jsitarek**, we should go for a re-creation of all sim_telarray files produced so far, with no changes in LST configuration. No need to keep the current sim_telarray files, but better to replace them only once all the new ones are ready.

**Comment by jsitarek** [comment]
@moralejo, @Voutsi 

while investigating some other settings I found another problem that needs fixing at the sim_telarray level (for MAGIC2). Let me close this issue and open another one
