### ISSUE TITLE
Revert change of MAGIC focal length to 17.0 m

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/lst-sim-config#47]
Discussing with @moralejo and checking the MAGIC simulation config files, we think the value of 16.97 m was actually correct before.

We think the correct values (as used by MAGIC reflector) are:

```
focal_length  = 1697
dish_shape_length = 1697
focus_offset = 3
```

focal_length + focus_offset is distance from dish to camera, which are the 17 m.

**Comment by moralejo** [comment]
At least that seems to be the way the MAGIC simulations are configured. I anyway think it would have a quite negligible effect, as long as the focusing is at ~10 km. The difference in the plate scale would be 0.18%, way smaller than e.g. the coma aberration effect (which we so often forget ;)

**Comment by jsitarek** [comment]
Thanks for reporting this @maxnoe. Let me add some more details for bookkeeping in case we wonder about this again in the future. 

Indeed in the MagicSoft reflector mirror files the focal distance (paraboloid_focal) is 1697 cm and distance to the camera (focal_distance) is 1700. 
As far as I can see in sim_telarray it is used such that focal_length is the nominal focal length of the mirrors, and focus_offset is the distance of the entrance of the light guides behind the focal point. The way it is used (most importantly in sim_imaging.c):
```
make_trafo(-cam_rot,M_PI,0., 0.,0.,flen+focus_offset-overall_offset, ctrans);
```
so the focus_offset is added to the focal length when computing the distance 

And I fully agree with @moralejo, the difference would be ~0.0035 deg at the edge of the camera, way below all the other scales (coma, pixel size, angular resolution), so it should not affect the performance. 

I will make the changes

EDIT:
we also have the effective_focal_length computed as 1700*1.0713, but this one I guess should stay as it is, because the actual distance to the mirror is the more relevant here. Nevertheless, as with the nominal focal length it will also make very little difference.

**Comment by jsitarek** [comment]
Hi @moralejo 
why did you close the issue? The linked PR is not yet merged (I wanted to see if @maxnoe has any comments since he reported the issue)

**Comment by moralejo** [comment]
Sorry, I thought there was nothing else to discuss here...

**Comment by maxnoe** [comment]
Now it's merged...
